// <auto-generated />
using System;
using MeleeSearch.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeleeSearch.Data.Migrations
{
    [DbContext(typeof(MeleeSearchDbContext))]
    [Migration("20260112131908_AddCharacterSupport")]
    partial class AddCharacterSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeleeSearch.Models.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("MeleeSearch.Models.Entities.DataEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_data_entries_created_at");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_data_entries_title");

                    b.HasIndex("type")
                        .HasDatabaseName("idx_data_entries_type");

                    b.ToTable("data_entries", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("DataEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MeleeSearch.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("data_entry_characters", b =>
                {
                    b.Property<int>("data_entry_id")
                        .HasColumnType("integer");

                    b.Property<int>("character_id")
                        .HasColumnType("integer");

                    b.HasKey("data_entry_id", "character_id");

                    b.HasIndex("character_id");

                    b.ToTable("data_entry_characters");
                });

            modelBuilder.Entity("data_entry_tags", b =>
                {
                    b.Property<int>("data_entry_id")
                        .HasColumnType("integer");

                    b.Property<int>("tag_id")
                        .HasColumnType("integer");

                    b.HasKey("data_entry_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("data_entry_tags");
                });

            modelBuilder.Entity("MeleeSearch.Models.Entities.CharacterAttribute", b =>
                {
                    b.HasBaseType("MeleeSearch.Models.Entities.DataEntry");

                    b.HasDiscriminator().HasValue("character_attribute");
                });

            modelBuilder.Entity("MeleeSearch.Models.Entities.FrameData", b =>
                {
                    b.HasBaseType("MeleeSearch.Models.Entities.DataEntry");

                    b.HasDiscriminator().HasValue("frame_data");
                });

            modelBuilder.Entity("data_entry_characters", b =>
                {
                    b.HasOne("MeleeSearch.Models.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeleeSearch.Models.Entities.DataEntry", null)
                        .WithMany()
                        .HasForeignKey("data_entry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data_entry_tags", b =>
                {
                    b.HasOne("MeleeSearch.Models.Entities.DataEntry", null)
                        .WithMany()
                        .HasForeignKey("data_entry_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeleeSearch.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
